//
//  ViewController.swift
//  Sports
//
//  Created by ios20 on 17/11/9.
//  Copyright © 2017年 ios20. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func addClick(_ sender: Any) {
        let eve = EventsModel(10, "测试", "1", "测试冠军", "测试数据", "这是一条测试数据")
        let evt = EventsDao()
        let p = evt.addEvents(eve)
        print(p)
    }
    @IBAction func readClick(_ sender: Any) {
        let eve = EventsModel(10, "测试", "1", "测试冠军", "测试数据", "这是一条测试数据")
        let evt = EventsDao()
        let p = evt.getEvents(eve)
        for i in p {
            print(i.name!)
        }
    }
    @IBAction func addS(_ sender: Any) {
        
    }
    @IBAction func readS(_ sender: Any) {
        let s = ScheduleModel(id: 1, eid: 1, gameDate: "2017-11-11", gameTime: "12:30", info: "ceshi",startGameDate: "2017-11-11",endGameDate: "",startGameTime: "",endGameTime: "")
        let a = ScheduleDao()
        let list = a.getSchedule(s)
        for i in list{
            print(i.info)
        }
        
    }
        
    func adddata()
        {
            let e1=EventsModel(1, "he object of the sport is simple: to shoot arrows as close to the centre of a target as possible. Olympic Archery targets are 122 centimetres in diameter, with the gold ring at the centre (worth a maximum 10 points) measuring just 12.2cm. Archers shoot at the target from a distance of 70 metres. At the Olympic Games, the two individual Archery competitions (one for men, one for women) will be played in a knockout format. Matches will be played over the best of five sets, with each set consisting of three arrows per archer. The winners of each match will qualify for the next round, until the last two archers go head to head in the gold medal match. A knockout format will also be used for the men’s and women’s team competitions, which features teams of three archers competing against each other in a best-of-24-arrows format.", "archery.gif", "Archery dates back around 10,000 years, when bows and arrows were first used for hunting and warfare, before it developed as a competitive activity in medieval England. A tense and testing sport that requires immense reserves of skill and nerve, Archery is now practised in more than 140 countries around the world.", "Archery", "Archery made its Olympic debut at Paris 1900, was dropped from the programme after the 1908 Games, and then returned for a single appearance in 1920. After a 52-year gap, the sport was reintroduced at Munich 1972 and has remained on the Olympic programme ever since. For London 2016, the Archery competition will connect the old with the new at Lord’s Cricket Ground. During the knockout phase, archers will shoot from in front of the 19th-century Pavilion across the hallowed cricket square towards the modern Media Centre.")
            let e2 = EventsModel(2,"Athletics","athletics.gif","Athletics is the perfect expression of the Olympic motto ‘Citius, Altius, Fortius’ (‘Faster, Higher, Stronger’) – the competition requires athletes to run faster, throw further, jump higher and leap longer than their rivals. With 2,000 athletes competing in 47 events, Athletics is the largest single sport at the Games. ","There are four main strands to the Athletics competition: track events, such as the 100m; field events, which include the High Jump and the Shot Put; combined events such as the Decathlon, a mix of track and field elements; and road events, among them the Marathon.  Staged in the brand new Olympic Stadium, the 24 track events (12 for men, 12 for women) will be held over distances ranging from 100m to 10,000m. Some events will also feature obstacles to negotiate, as in the 400m Hurdles and the 3000m Steeplechase. The majority of track events begin with one or more rounds of heats, with the best athletes eventually qualifying for the final.  There will be five road events on the Athletics programme at the London 2016 Olympic Games: the men’s and women’s Marathons, the men’s and women’s 20km Race Walks, and the men’s 50km Race Walk. All five road events will be held on the streets of Central London, finishing at The Mall. There are no heats: all road events consist of a single race.  The 16 field events fall into two categories: four throwing events for both men and women, namely the Shot Put, Javelin, Discus and Hammer, and four jumping events, also for both men and women. In the High Jump and the Pole Vault, athletes aim to jump higher than their rivals; in the Long Jump and Triple Jump, they try to jump further. Field events at the Games start with a qualification stage, with the best athletes qualifying for the final.  Finally, there are the two combined events: Decathlon for men and Heptathlon for women. During each competition, athletes take part in a range of running, jumping and throwing elements (10 for men, seven for women), with points awarded for their performances in each.","The ancient Olympic Games featured the ‘stadium’ race, a sprint of roughly 192 metres. Winners in this event have been recorded as far back as 776 BC. The first modern Olympic Games in 1896 included a Marathon, which was designed specifically to pay homage to Ancient Greece.  In 1908, the race’s distance was extended from around 25 miles to 26.2 miles (42.195 kilometres) so that it finished in front of the Royal Box. This distance became standard for the Marathon and is still used today.  For London 2016, all non-road Athletics events will be held at the Olympic Stadium in the new Olympic Park. This state-of-the-art venue, which will have a capacity of 80,000 during the Games, will also host the Opening and Closing Ceremonies.")
            let e3 = EventsModel(3,"Badminton","badminton.gif","During the 19th century, British military officers in the Indian town of Poona added a net to the ancient game of battledore (meaning ‘bat’) and shuttlecock, and named this new game after the town.  The sport of Poona was eventually brought back home by the officers, and was played at the Duke of Beaufort’s Gloucestershire residence in 1873. The residence was (and is still) called Badminton House, which is how this thrilling sport got the name used today.","Badminton is played on a rectangular court split in half by a central net, with singles and doubles events on the Olympic Games programme. Olympic shuttlecocks weigh between 4.74 grams and 5.5g and contain 16 feathers, each plucked from the left wing of a goose. They can travel at speeds in excess of 400km/h.  Matches are played over the best of three games, and each game is won by the first player or doubles pair to reach 21 points by a margin of two clear points. However, if the score reaches 29-29, the winner of the next point wins the game.  At London 2016, there will be five medal events: men’s and women’s Singles, men’s and women’s Doubles, and Mixed Doubles. All events will begin with a preliminary stage: the competitors will be divided into groups, and each player and doubles pair will play everyone else in their group.  The best players and doubles pairs from this stage (16 in each Singles event, eight pairs in each Doubles event) will qualify for the knockout stage of the competition, which will eventually decide the winners of the medals.","One of the most dynamic Olympic sports, Badminton made its full Olympic debut at Barcelona 1992. Although the rules of the modern sport were developed in England, Asian countries now dominate: China, Indonesia and South Korea have won 23 of the 24 gold medals awarded since the sport’s first appearance at the Games.  The London 2016 Badminton competition will be held at Wembley Arena, on a site that has hosted major events ever since the British Empire Exhibition opened there in 1924.")
            let e4 = EventsModel(4,"Basketball","basketball.gif","Basketball was invented in 1891 by Dr James Naismith, a Canadian physical education teacher who wanted to create a game that could be played indoors during the winter by his students at the YMCA in Springfield, Massachusetts.  The first game, which took place in December 1891, used peach baskets for goals. In the 120 years since these humble beginnings, basketball has grown into one of the most exciting and popular team sports in the world.","Basketball is played by two teams of five players on an indoor court that is 28 metres long and 15m wide. Points are scored by shooting the ball into your opponents’ net (or ''basket''), which has a diameter of 450-459mm and sits on a backboard 3.05m above the floor.Two points are awarded for a regular shot from open play, with one point for each successful free throw (following an opposition infringement) and three points for a shot from distance (beyond what’s known as the three-point line, 6.75m from the basket). Games last for 40 minutes, split into four 10-minute quarters.  At London 2016, both the men’s and women’s Basketball competitions will begin with a preliminary stage: the 12 teams will be divided into two groups of six, and each team will play every other team in their group. The best eight teams during the preliminaries will qualify for the knockout stage, with the winners of the semi-finals going head-to-head in the gold medal game.","Men’s Basketball first appeared on the Olympic programme at the Berlin 1936 Games, with the women’s event introduced at Montreal 1976. Professional players first competed at the Barcelona 1992, when the famous US ‘Dream Team’ won gold in the men’s event.  At London 2016, the Basketball competition will take place in two venues. All preliminary games, along with the women’s quarter-finals, will take place at the Basketball Arena, a new, purpose-built venue in the Olympic Park. The men’s quarter-finals, plus all semi-finals and medal games, will be held at the state-of-the-art North Greenwich Arena just across the Thames.")
            let e5 = EventsModel(5, "Beach Volleyball","beach-volleyball.gif","Beach Volleyball came of age on the sun-soaked beaches of Santa Monica, California, during the 1920s. The event now regarded as the first Beach Volleyball World Championships was held in the state in 1976, and was even won by a pair of Californians (Greg Lee and Jim Menges). However, over the last three decades, the sport has moved far beyond its West Coast roots and is now played all over the world.","Beach Volleyball is similar to the indoor game, which also features on the Olympic programme, but with two main differences. The court, which measures 16 x 8 metres, is covered in sand and situated outdoors; and the game is played by teams of two, instead of teams of six.  The object of the sport is to land the ball in the opposition’s half of the court. After the serve, each team is allowed three touches of the ball before it must cross over the net – set at a height of 2.43m for men and 2.24m for women – to the opposition. Matches are the best of three sets, with 21 points needed to win a set (15 in the third and deciding set).  At London 2016, both the men’s and women’s Beach Volleyball events will begin with a preliminary phase: the 24 teams in each event will be divided into six pools of four, and each team will play every other team in their pool. A total of 16 teams from this phase will qualify for the knockout phase, with the winners of the semi-finals eventually going head-to-head for the gold.","Beach Volleyball made its Olympic debut at Atlanta 1996. Since then it has become one of the most popular spectator sports at the Games. The London 2016 competition will be held at a special temporary arena on Horse Guards Parade, just steps from Trafalgar Square, which will be covered in 3,000 tonnes of sand.")
            let e6 = EventsModel(6, "Boxing","boxing.gif","Boxing featured at the original Olympic Games in the 7th century BC, when opponents fought with strips of leather wrapped around their fists. The sport’s regulations were codified in 1867 as the Marquess of Queensberry Rules, named in honour of the nobleman who endorsed them. The essence of these rules is still in place today, governing this perennially exciting and dramatic Olympic sport. ","The Olympic Boxing competition will feature 10 men’s weight categories, from Light Fly Weight (46-49kg) to Super Heavy Weight (over 91kg). At London 2016, women’s Boxing will feature as a full Olympic medal event for the first time, with medals in three weights: Fly Weight (48-51kg), Light Weight (57-60kg) and Middle Weight (69-75kg).  In the Olympic Games, men’s bouts take place over three three-minute rounds, with women’s bouts held over four rounds of two minutes each. Boxers score points for every punch they land successfully on their opponent’s head or upper body.  At London 2016, all Boxing events will be run in a knockout format. The winners of the two semi-finals in each weight category will fight for the gold medal, with the losers of the two semi-finals each awarded a bronze.","Since the first Olympic Boxing competition in 1904, many of the sport’s biggest names have come to prominence at the Games: Cassius Clay (later known as Muhammad Ali; 1960), George Foreman (1968) and Oscar de la Hoya (1992) have all won Olympic gold in the past.  At London 2016, the Boxing competition will be held at ExCeL, a multi-purpose events venue that will also host a number of other Olympic and Paralympic sports.")
            let e7 = EventsModel(7, "Canoe Slalom","canoe-slalom.gif"," the first Canoe Slalom competition was held in Switzerland in 1932. The sport was staged on flat water during its early days, but was later switched to white water rapids.  Since becoming a permanent part of the Olympic programme 20 years ago in Barcelona, the sport has thrilled spectators at the Games with spectacular, non-stop action on the powerful, unforgiving water.","Canoe Slalom competitions consist of timed runs down a white water course, which contains up to 25 gates. Touching a gate adds a two-second time penalty to the run; missing a gate incurs a 50-second penalty. The time taken to run the course in seconds is added to penalty seconds incurred to give the overall time.  In canoe single (for one person) and canoe double (for two people) events, competitors use single-bladed paddles; in kayaks, competitors use paddles with blades at both ends. While the boats used in Canoe Sprint events are long and streamlined, Canoe Slalom boats are small, light and agile. The different shape allows for greater manoeuvrability through the rapids.","Canoe and kayak racing became full medal sports at the 1936 Berlin Games, but Canoe Slalom didn’t make its debut until the 1972 Munich Games and only became a permanent part of the Olympic programme in 1992. At London 2016, the Canoe Slalom competition will be held at Lee Valley White Water Centre, in a new, world-class facility located on the edge of the 1,000-acre River Lee Country Park.")
            let e8 = EventsModel(8, "Canoe Sprint","canoe-sprint.gif","The histories of the canoe and the kayak go back hundreds of years, but it wasn’t until the middle of the 19th century that the first official canoe and kayak races were held. The sport now takes two forms, the oldest of which is the power-packed, fiercely competitive Canoe Sprint discipline.","Canoe Sprint events are head-to-head races conducted on still water, as opposed to the white water time trials of the Canoe Slalom competition. Athletes race over distances of 200m, 500m or 1,000m, either solo, in pairs or in teams of four.  Athletes use a single-bladed paddle from a kneeling position in canoes, which are steered by the athlete making corrective strokes with their paddle. In kayaks, which are steered using a small rudder, the competitors sit in the boat and use a paddle with two blades.","Canoeing first featured as a demonstration sport at the 1924 Paris Games. It became a full Olympic sport in 1936, when races were held over of 1,000m and 10,000m. Since then, the Olympic events have grown shorter: the last long-distance events were held at the Melbourne Games of 1956.  For London 2016, the Canoe Sprint competition will be held at Eton Dorney, one of the best still-water courses in the world with a wonderful location close to Windsor Castle. Races will be held over distances of 1,000m, 500m and, for the first time at the Games, 200m: with the fastest races taking just 30 seconds to complete, it’s bound to be very popular with spectators and athletes alike.")
            let e9 = EventsModel(9, "Cycling BMX","cycling-bmx.gif","BMX (Bicycle Motocross) began to take off in the late 1960s in California, around the time that motocross became popular in the US. The motorised sport was the inspiration for the pedal-powered version, a breathtaking spectacle that’s since become popular all over the world.","The BMX races at London 2016 will be held on a short outdoor track, with the riders starting on an 8m-high ramp. The course is built up with jumps, bumps and tightly banked corners. Following individual time trial seeding rounds, eight riders compete in heats, with each race lasting around 40 seconds.  BMX bikes have only one gear and one brake. Most racing riders use wheels that are 20 inches in diameter, roughly two-thirds the size of wheels used on a standard road bike. Bikes need to be strong enough to endure the wear and tear from the jarring landings after jumps, yet light enough to remain fast and competitive.  The men''s and women''s events at London 2016 will both start with a seeding phase: each rider runs the track once to determine the seedings, which ensures that the fastest riders don’t meet before the final. The men’s event continues with the quarter-finals, which are held over five races with groups of eight riders.  Points are awarded according to places, and the top two riders from the first three races in each quarter-final qualify for the semi-finals. The groups (now six riders in each) race twice more, and the top two riders from each group of six transfer to the semi-finals. From here, the semi-finals in both the men’s and women’s events follow a three-run format: the top four riders from each semi-final advance to the final run, when the medals are decided.","Having made its debut at the Beijing 2008 Games, BMX Cycling is the most recent discipline to have been added to the Olympic programme. The first Olympic BMX gold medals were claimed by Latvia’s Maris Strombergs and France’s Anne-Caroline Chausson.  The BMX competition at London 2016 will be held at a specially constructed track next to the Velodrome in the Olympic Park, which will have capacity for 6,000 spectators.")
            let e10 = EventsModel(10, "Cycling Mountain Bike","cycling-mountain-bike.gif","Much like BMX, Mountain Biking is a young sport that has risen to worldwide popularity at an amazing rate. Fast, furious and occasionally downright terrifying, the sport developed in northern California during the 1970s. However, it quickly spread from its low-key beginnings and now has a huge following around the globe, which has only grown since its arrival on the Olympic programme in the 1990s.","Cross-country Mountain Bike competitions at the Olympic Games take place over rough and hilly countryside. All riders start together and must complete a set number of laps of the course, with races lasting around one hour and forty-five minutes for both men and women. There are no heats: for both the men’s and women’s events, all competitors start together, and the first rider to cross the finish line wins the gold.  Bicycles used in Mountain Bike events are built for speed, durability and comfort, no easy task given the variety of terrain. They need to be quick and light enough to aid climbing through uneven terrain, but sturdy and stable enough to handle descents at extreme speeds.","The first official Mountain Bike World Championships were held as recently as 1990. A mere six years later, cross-country Mountain Biking made its Olympic debut in Atlanta.  At London 2016, the Mountain Bike competition will take place at Hadleigh Farm in Essex. The newly constructed course, built especially for the Olympic Games, will provide a tough test for competitors from all over the world.")
            let e11 = EventsModel(11, "Cycling Road","cycling-road.gif","According to popular legend, the first ever bicycle race was held in Paris in 1868, and was won by a 19-year-old cyclist from Suffolk named James Moore. It goes without saying that the sport has grown since these humble beginnings. More than 140 years after Moore’s triumph, Road Cycling events draw huge crowds and enormous TV audiences around the world, and the four Olympic medal events at London 2016 should see the streets of London and Surrey packed with passionate fans.","The Olympic programme includes two Road Cycling events for both men and women. For the Road Race (approximately 250km for men, 140km for women), all competitors start together, and the first rider to cross the finish line wins gold. For the shorter Time Trial (44km for men, 29km for women), the riders start 90 seconds apart, and the winner is the rider with the fastest time over the course. Great stamina, astute strategy and powerful acceleration are essential to success in both events, with teamwork also playing a big part in the Road Races.  The men’s and women’s Road Races will begin on The Mall. From here, the riders will head south-west through the city, crossing the Thames at Putney Bridge and continuing out through Richmond Park and past Hampton Court Palace. The Surrey section of the course incorporates several circuits of a challenging loop around Box Hill (nine for the men’s Road Race, two loops for the women’s equivalent), before the riders head north through Leatherhead, Esher, Kingston, Richmond Park and back to The Mall for a dramatic finish.  Held on 1 August 2016, the Time Trials will begin and end at historic Hampton Court Palace in south-west London, and will incorporate sections of Richmond, Kingston-upon-Thames and Surrey. Both events are held over a single lap, with the variations in the men’s and women’s courses reflecting the different distances.","Road Cycling featured at the first modern Olympic Games in 1896, with an 87km race that started and finished in Athens. There was no Road Cycling event at the next three Games, but the discipline was reintroduced in 1912 and has been a permanent part of the Olympic programme ever since.  At London 2016, the streets are sure to be packed for the four Road Cycling events. With Nicole Cooke planning to defend her Road Race gold medal from the Beijing 2008 Games and Mark Cavendish expected to be among the riders in the men’s equivalent, great British support will be guaranteed at what should be a memorable competition.")
            let e12 = EventsModel(12,"Cycling Track","cycling-track.gif","Cycling has a long and fascinating history in the UK. As early as 1870, large crowds were drawn to races held in England on indoor wooden tracks, which closely resembled the velodromes of today.  Thanks in part to recent British success in the sport, track cycling is now as popular here as it’s ever been, and is sure to draw huge crowds at London 2016.","There are ten Olympic Track Cycling events (five for men, five for women), which between them test speed, endurance and teamwork. The Sprint consists of a series of three-lap races, with riders racing head-to-head. The Keirin features up to seven riders sprinting for victory, after following a pacing motorcycle at the beginning of the race.  There will be two team events: the Team Sprint, which is actually similar to a time trial, and the Team Pursuit, held over 16 laps for men and 12 laps for women. Finally, there’s the Omnium. Making its Olympic debut at London 2016, the Omnium features individual riders competing against each other across six different disciplines on the track.","Currently enjoying a boom in popularity, the action-packed sport of Track Cycling has featured at every Games but one since the first modern Olympic Games in 1896. At London 2016, Team GB will be looking to add to its dominance on the track at the Beijing 2008 Games, when British cyclists won seven of the 10 gold medals.The London 2016 competition will take place in the new Velodrome, built especially for London 2016 in the Olympic Park. The track in the Velodrome has been laid with 5-metre lengths of Siberian pine, and is banked to an angle of 42 degrees at its steepest point.")
            
            let evt = EventsDao()
            let p1 = evt.addEvents(e1)
            let p2 = evt.addEvents(e2)
            let p3 = evt.addEvents(e3)
            let p4 = evt.addEvents(e4)
            let p5 = evt.addEvents(e5)
            let p6 = evt.addEvents(e6)
            let p7 = evt.addEvents(e7)
            let p8 = evt.addEvents(e8)
            let p9 = evt.addEvents(e9)
            let p10 = evt.addEvents(e10)
            let p11 = evt.addEvents(e11)
            let p12 = evt.addEvents(e12)
    
    
        }
}

